export const FETCH_TAGS_ACTION = 'FETCH_TAGS_ACTION';
export const FETCH_TAGS_SUCCESS_ACTION = 'FETCH_TAGS_SUCCESS_ACTION';
export const FETCH_TAGS_FAILURE_ACTION = 'FETCH_TAGS_FAILURE_ACTION';

export const FETCH_TAG_END_POINT = '/tags'