export const NEW_ARTICLE_POST_ACTION = 'NEW_ARTICLE_POST_ACTION';
export const NEW_ARTICLE_POST_ACTION_SUCCESS_ACTION = 'NEW_ARTICLE_POST_ACTION_SUCCESS_ACTION';
export const NEW_ARTICLE_POST_ACTION_FAILURE_ACTION = 'NEW_ARTICLE_POST_ACTION_FAILURE_ACTION';

export const  NEW_ARTICLE_POST_END_POINT = '/articles'