export const FETCH_USER_FEED_ACTION = 'FETCH_USER_FEED_ACTION';
export const FETCH_USER_FEED_SUCCESS_ACTION = 'FETCH_USER_FEED_SUCCESS_ACTION';
export const FETCH_USER_FEED_FAILURE_ACTION = 'FETCH_USER_FEED_FAILURE_ACTION';

export const FETCH_USER_FEED_END_POINT = '/articles/feed'