//Sign up actions
export const USER_SIGNUP_ACTION = 'USER_SIGNUP_ACTION';
export const USER_SIGNUP_SUCCESS_ACTION = 'USER_SIGNUP_SUCCESS_ACTION';
export const USER_SIGNUP_FAILURE_ACTION = 'USER_SIGNUP_FAILURE_ACTION';

//Sign in actions
export const USER_SIGIN_ACTION = 'USER_SIGIN_ACTION';
export const USER_SIGIN_SUCCESS_ACTION = 'USER_SIGIN_SUCCESS_ACTION';
export const USER_SIGIN_FAILURE_ACTION = 'USER_SIGIN_FAILURE_ACTION';

export const REGISTER_USER_API_END_POINT = '/users';
export const LOGIN_USER_API_END_POINT = '/users/login';