export const FETCH_GLOBAL_FEED_ACTION = 'FETCH_GLOBAL_FEED_ACTION';
export const FETCH_GLOBAL_FEED_SUCCESS_ACTION = 'FETCH_GLOBAL_FEED_SUCCESS_ACTION';
export const FETCH_GLOBAL_FEED_FAILURE_ACTION = 'FETCH_GLOBAL_FEED_FAILURE_ACTION';

export const FETCH_GLOBAL_FEED_END_POINT = '/articles'