export const USER_SETTING_SAVE_ACTION = 'USER_SETTING_SAVE_ACTION';
export const USER_SETTING_SAVE_SUCCESS_ACTION = 'USER_SETTING_SAVE_SUCCESS_ACTION';
export const USER_SETTING_SAVE_FAILURE_ACTION = 'USER_SETTING_SAVE_FAILURE_ACTION';
export const USER_LOGOUT_ACTION = 'USER_LOGOUT_ACTION';

export const USER_SETTING_SAVE_END_POINT = '/user'